create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null default '',
  role text not null default 'caixa' check (role in ('admin','caixa')),
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nome, role, ativo)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(coalesce(new.email,''), '@', 1), 'Usuário'),
    'caixa',
    true
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, nome, role, ativo)
select
  u.id,
  coalesce(u.raw_user_meta_data->>'name', split_part(coalesce(u.email,''), '@', 1), 'Usuário'),
  'caixa',
  true
from auth.users u
on conflict (id) do nothing;

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid() and ativo = true
  limit 1;
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_role() in ('admin','caixa'), false);
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_role() = 'admin', false);
$$;

revoke all on function public.current_role() from public;
revoke all on function public.is_staff() from public;
revoke all on function public.is_admin() from public;
grant execute on function public.current_role() to authenticated;
grant execute on function public.is_staff() to authenticated;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.vendedores (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique,
  nome text not null,
  telefone text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.produtos (
  id uuid primary key default gen_random_uuid(),
  codigo_barras text unique,
  nome text not null,
  categoria text,
  preco_compra numeric(12,2) not null default 0 check (preco_compra >= 0),
  preco_venda numeric(12,2) not null check (preco_venda >= 0),
  estoque numeric(12,3) not null default 0,
  estoque_minimo numeric(12,3) not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists produtos_nome_idx on public.produtos (nome);
create index if not exists produtos_codigo_barras_idx on public.produtos (codigo_barras);

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  telefone text,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.caixas (
  id uuid primary key default gen_random_uuid(),
  aberto_por uuid not null references auth.users(id),
  aberto_em timestamptz not null default now(),
  saldo_inicial numeric(12,2) not null default 0 check (saldo_inicial >= 0),
  fechado_por uuid references auth.users(id),
  fechado_em timestamptz,
  saldo_final_informado numeric(12,2),
  observacao text,
  status text not null default 'aberto' check (status in ('aberto','fechado'))
);

create unique index if not exists apenas_um_caixa_aberto
on public.caixas ((1))
where status = 'aberto';

create table if not exists public.vendas (
  id bigint generated by default as identity primary key,
  caixa_id uuid not null references public.caixas(id),
  vendedor_id uuid not null references public.vendedores(id),
  cliente_id uuid references public.clientes(id),
  tipo_pagamento text not null check (tipo_pagamento in ('Dinheiro','Cartão','Pix','Fiado')),
  subtotal numeric(12,2) not null default 0,
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  total numeric(12,2) not null default 0,
  custo_total numeric(12,2) not null default 0,
  lucro numeric(12,2) not null default 0,
  fiado boolean not null default false,
  quitado boolean not null default true,
  status text not null default 'concluida' check (status in ('concluida','cancelada')),
  observacao text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  cancelada_por uuid references auth.users(id),
  cancelada_em timestamptz,
  motivo_cancelamento text
);

create index if not exists vendas_created_at_idx on public.vendas(created_at desc);
create index if not exists vendas_vendedor_idx on public.vendas(vendedor_id);
create index if not exists vendas_cliente_idx on public.vendas(cliente_id);

create table if not exists public.venda_itens (
  id bigint generated by default as identity primary key,
  venda_id bigint not null references public.vendas(id) on delete restrict,
  produto_id uuid not null references public.produtos(id),
  produto_nome text not null,
  quantidade numeric(12,3) not null check (quantidade > 0),
  preco_unitario numeric(12,2) not null check (preco_unitario >= 0),
  custo_unitario numeric(12,2) not null check (custo_unitario >= 0),
  total numeric(12,2) not null check (total >= 0)
);

create table if not exists public.movimentacoes_estoque (
  id bigint generated by default as identity primary key,
  produto_id uuid not null references public.produtos(id),
  venda_id bigint references public.vendas(id),
  tipo text not null check (tipo in ('venda','cancelamento','entrada','ajuste','perda')),
  quantidade numeric(12,3) not null,
  estoque_anterior numeric(12,3) not null,
  estoque_novo numeric(12,3) not null,
  motivo text,
  user_id uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.pagamentos_fiado (
  id bigint generated by default as identity primary key,
  venda_id bigint not null references public.vendas(id),
  caixa_id uuid not null references public.caixas(id),
  valor numeric(12,2) not null check (valor > 0),
  tipo_pagamento text not null check (tipo_pagamento in ('Dinheiro','Cartão','Pix')),
  recebido_por uuid not null references auth.users(id),
  observacao text,
  created_at timestamptz not null default now()
);

create table if not exists public.configuracoes (
  id integer primary key default 1 check (id = 1),
  nome_empresa text not null default 'CAHK - Centro Acadêmico Hugo Kremer',
  cnpj text,
  endereco text,
  telefone text,
  mensagem_rodape text default 'Obrigado!',
  largura_impressao integer not null default 80 check (largura_impressao in (58,80)),
  updated_at timestamptz not null default now()
);

insert into public.configuracoes (id) values (1) on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.vendedores enable row level security;
alter table public.produtos enable row level security;
alter table public.clientes enable row level security;
alter table public.caixas enable row level security;
alter table public.vendas enable row level security;
alter table public.venda_itens enable row level security;
alter table public.movimentacoes_estoque enable row level security;
alter table public.pagamentos_fiado enable row level security;
alter table public.configuracoes enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists vendedores_staff_select on public.vendedores;
create policy vendedores_staff_select on public.vendedores for select to authenticated using (public.is_staff());
drop policy if exists produtos_staff_select on public.produtos;
create policy produtos_staff_select on public.produtos for select to authenticated using (public.is_staff());
drop policy if exists clientes_staff_select on public.clientes;
create policy clientes_staff_select on public.clientes for select to authenticated using (public.is_staff());
drop policy if exists caixas_staff_select on public.caixas;
create policy caixas_staff_select on public.caixas for select to authenticated using (public.is_staff());
drop policy if exists vendas_staff_select on public.vendas;
create policy vendas_staff_select on public.vendas for select to authenticated using (public.is_staff());
drop policy if exists itens_staff_select on public.venda_itens;
create policy itens_staff_select on public.venda_itens for select to authenticated using (public.is_staff());
drop policy if exists fiado_staff_select on public.pagamentos_fiado;
create policy fiado_staff_select on public.pagamentos_fiado for select to authenticated using (public.is_staff());
drop policy if exists config_staff_select on public.configuracoes;
create policy config_staff_select on public.configuracoes for select to authenticated using (public.is_staff());
drop policy if exists mov_admin_select on public.movimentacoes_estoque;
create policy mov_admin_select on public.movimentacoes_estoque for select to authenticated using (public.is_admin());

drop policy if exists vendedores_admin_insert on public.vendedores;
create policy vendedores_admin_insert on public.vendedores for insert to authenticated with check (public.is_admin());
drop policy if exists vendedores_admin_update on public.vendedores;
create policy vendedores_admin_update on public.vendedores for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists vendedores_admin_delete on public.vendedores;
create policy vendedores_admin_delete on public.vendedores for delete to authenticated using (public.is_admin());

drop policy if exists produtos_admin_insert on public.produtos;
create policy produtos_admin_insert on public.produtos for insert to authenticated with check (public.is_admin());
drop policy if exists produtos_admin_update on public.produtos;
create policy produtos_admin_update on public.produtos for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists produtos_admin_delete on public.produtos;
create policy produtos_admin_delete on public.produtos for delete to authenticated using (public.is_admin());

drop policy if exists clientes_staff_insert on public.clientes;
create policy clientes_staff_insert on public.clientes for insert to authenticated with check (public.is_staff());
drop policy if exists clientes_staff_update on public.clientes;
create policy clientes_staff_update on public.clientes for update to authenticated using (public.is_staff()) with check (public.is_staff());
drop policy if exists clientes_admin_delete on public.clientes;
create policy clientes_admin_delete on public.clientes for delete to authenticated using (public.is_admin());

drop policy if exists config_admin_update on public.configuracoes;
create policy config_admin_update on public.configuracoes for update to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.abrir_caixa(p_saldo_inicial numeric default 0)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare v_id uuid;
begin
  if auth.uid() is null or not public.is_staff() then raise exception 'Não autorizado'; end if;
  if coalesce(p_saldo_inicial, 0) < 0 then raise exception 'Saldo inicial inválido'; end if;
  if exists (select 1 from public.caixas where status = 'aberto') then raise exception 'Já existe um caixa aberto'; end if;
  insert into public.caixas (aberto_por, saldo_inicial)
  values (auth.uid(), coalesce(p_saldo_inicial,0))
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.fechar_caixa(p_saldo_final_informado numeric, p_observacao text default null)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare v_id uuid;
begin
  if auth.uid() is null or not public.is_staff() then raise exception 'Não autorizado'; end if;
  select id into v_id from public.caixas where status = 'aberto' order by aberto_em desc limit 1 for update;
  if v_id is null then raise exception 'Não há caixa aberto'; end if;
  update public.caixas set status='fechado', fechado_por=auth.uid(), fechado_em=now(),
    saldo_final_informado=p_saldo_final_informado, observacao=p_observacao where id=v_id;
  return v_id;
end;
$$;

create or replace function public.finalizar_venda(
  p_vendedor_id uuid,
  p_tipo_pagamento text,
  p_cliente_id uuid default null,
  p_desconto numeric default 0,
  p_observacao text default null,
  p_itens jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_caixa_id uuid;
  v_venda_id bigint;
  v_item jsonb;
  v_produto public.produtos%rowtype;
  v_qtd numeric(12,3);
  v_subtotal numeric(12,2) := 0;
  v_custo numeric(12,2) := 0;
  v_total numeric(12,2);
  v_desconto numeric(12,2) := greatest(coalesce(p_desconto,0),0);
  v_estoque_anterior numeric(12,3);
  v_fiado boolean;
begin
  if auth.uid() is null or not public.is_staff() then raise exception 'Não autorizado'; end if;
  if p_tipo_pagamento not in ('Dinheiro','Cartão','Pix','Fiado') then raise exception 'Forma de pagamento inválida'; end if;
  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens) = 0 then raise exception 'Carrinho vazio'; end if;
  if not exists (select 1 from public.vendedores where id=p_vendedor_id and ativo=true) then raise exception 'Vendedor inválido ou inativo'; end if;

  select id into v_caixa_id from public.caixas where status='aberto' order by aberto_em desc limit 1 for update;
  if v_caixa_id is null then raise exception 'Abra o caixa antes de realizar vendas'; end if;

  v_fiado := (p_tipo_pagamento = 'Fiado');
  if v_fiado and (p_cliente_id is null or not exists (select 1 from public.clientes where id=p_cliente_id and ativo=true))
    then raise exception 'Venda fiada exige um cliente cadastrado'; end if;

  for v_item in select value from jsonb_array_elements(p_itens)
  loop
    v_qtd := nullif(v_item->>'quantidade','')::numeric;
    if v_qtd is null or v_qtd <= 0 then raise exception 'Quantidade inválida'; end if;
    select * into v_produto from public.produtos
      where id=(v_item->>'produto_id')::uuid and ativo=true for update;
    if not found then raise exception 'Produto inválido ou inativo'; end if;
    if v_produto.estoque < v_qtd then
      raise exception 'Estoque insuficiente para % (disponível: %)', v_produto.nome, v_produto.estoque;
    end if;
    v_subtotal := v_subtotal + round(v_produto.preco_venda * v_qtd,2);
    v_custo := v_custo + round(v_produto.preco_compra * v_qtd,2);
  end loop;

  if v_desconto > v_subtotal then raise exception 'Desconto maior que o subtotal'; end if;
  v_total := round(v_subtotal - v_desconto,2);

  insert into public.vendas (
    caixa_id,vendedor_id,cliente_id,tipo_pagamento,subtotal,desconto,total,custo_total,lucro,
    fiado,quitado,observacao,created_by
  ) values (
    v_caixa_id,p_vendedor_id,p_cliente_id,p_tipo_pagamento,v_subtotal,v_desconto,v_total,v_custo,
    round(v_total-v_custo,2),v_fiado,not v_fiado,p_observacao,auth.uid()
  ) returning id into v_venda_id;

  for v_item in select value from jsonb_array_elements(p_itens)
  loop
    v_qtd := (v_item->>'quantidade')::numeric;
    select * into v_produto from public.produtos where id=(v_item->>'produto_id')::uuid for update;

    insert into public.venda_itens (venda_id,produto_id,produto_nome,quantidade,preco_unitario,custo_unitario,total)
    values (v_venda_id,v_produto.id,v_produto.nome,v_qtd,v_produto.preco_venda,v_produto.preco_compra,
      round(v_produto.preco_venda*v_qtd,2));

    v_estoque_anterior := v_produto.estoque;
    update public.produtos set estoque=estoque-v_qtd, updated_at=now() where id=v_produto.id;

    insert into public.movimentacoes_estoque (
      produto_id,venda_id,tipo,quantidade,estoque_anterior,estoque_novo,motivo,user_id
    ) values (
      v_produto.id,v_venda_id,'venda',-v_qtd,v_estoque_anterior,v_estoque_anterior-v_qtd,
      'Venda #'||v_venda_id,auth.uid()
    );
  end loop;

  return jsonb_build_object('id',v_venda_id,'numero',v_venda_id,'subtotal',v_subtotal,
    'desconto',v_desconto,'total',v_total,'custo_total',v_custo,'lucro',round(v_total-v_custo,2));
end;
$$;

create or replace function public.ajustar_estoque(p_produto_id uuid,p_novo_estoque numeric,p_motivo text default 'Ajuste manual')
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare v_anterior numeric(12,3); v_delta numeric(12,3);
begin
  if auth.uid() is null or not public.is_admin() then raise exception 'Apenas administrador pode ajustar estoque'; end if;
  select estoque into v_anterior from public.produtos where id=p_produto_id for update;
  if v_anterior is null then raise exception 'Produto não encontrado'; end if;
  v_delta := p_novo_estoque-v_anterior;
  update public.produtos set estoque=p_novo_estoque,updated_at=now() where id=p_produto_id;
  insert into public.movimentacoes_estoque (produto_id,tipo,quantidade,estoque_anterior,estoque_novo,motivo,user_id)
    values (p_produto_id,'ajuste',v_delta,v_anterior,p_novo_estoque,p_motivo,auth.uid());
  return p_novo_estoque;
end;
$$;

create or replace function public.cancelar_venda(p_venda_id bigint,p_motivo text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare v_venda public.vendas%rowtype; v_item public.venda_itens%rowtype; v_estoque_anterior numeric(12,3);
begin
  if auth.uid() is null or not public.is_admin() then raise exception 'Apenas administrador pode cancelar venda'; end if;
  select * into v_venda from public.vendas where id=p_venda_id for update;
  if not found then raise exception 'Venda não encontrada'; end if;
  if v_venda.status='cancelada' then raise exception 'Venda já cancelada'; end if;
  if exists(select 1 from public.pagamentos_fiado where venda_id=p_venda_id) then
    raise exception 'Venda possui recebimentos de fiado. Revise antes de cancelar';
  end if;

  for v_item in select * from public.venda_itens where venda_id=p_venda_id
  loop
    select estoque into v_estoque_anterior from public.produtos where id=v_item.produto_id for update;
    update public.produtos set estoque=estoque+v_item.quantidade,updated_at=now() where id=v_item.produto_id;
    insert into public.movimentacoes_estoque (
      produto_id,venda_id,tipo,quantidade,estoque_anterior,estoque_novo,motivo,user_id
    ) values (
      v_item.produto_id,p_venda_id,'cancelamento',v_item.quantidade,v_estoque_anterior,
      v_estoque_anterior+v_item.quantidade,coalesce(p_motivo,'Cancelamento de venda'),auth.uid()
    );
  end loop;

  update public.vendas set status='cancelada',cancelada_por=auth.uid(),cancelada_em=now(),
    motivo_cancelamento=p_motivo where id=p_venda_id;
  return true;
end;
$$;

create or replace function public.receber_fiado(p_venda_id bigint,p_valor numeric,p_tipo_pagamento text,p_observacao text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_venda public.vendas%rowtype; v_caixa_id uuid; v_pago numeric(12,2); v_saldo numeric(12,2);
begin
  if auth.uid() is null or not public.is_staff() then raise exception 'Não autorizado'; end if;
  if p_tipo_pagamento not in ('Dinheiro','Cartão','Pix') then raise exception 'Forma de pagamento inválida'; end if;
  if p_valor is null or p_valor<=0 then raise exception 'Valor inválido'; end if;

  select * into v_venda from public.vendas where id=p_venda_id for update;
  if not found or not v_venda.fiado or v_venda.status<>'concluida' then raise exception 'Venda fiada inválida'; end if;

  select id into v_caixa_id from public.caixas where status='aberto' order by aberto_em desc limit 1;
  if v_caixa_id is null then raise exception 'Abra o caixa antes de receber fiado'; end if;

  select coalesce(sum(valor),0) into v_pago from public.pagamentos_fiado where venda_id=p_venda_id;
  v_saldo := v_venda.total-v_pago;
  if p_valor>v_saldo then raise exception 'Valor maior que o saldo devedor'; end if;

  insert into public.pagamentos_fiado (venda_id,caixa_id,valor,tipo_pagamento,recebido_por,observacao)
    values (p_venda_id,v_caixa_id,p_valor,p_tipo_pagamento,auth.uid(),p_observacao);

  v_pago:=v_pago+p_valor; v_saldo:=v_venda.total-v_pago;
  if v_saldo<=0 then update public.vendas set quitado=true where id=p_venda_id; v_saldo:=0; end if;
  return jsonb_build_object('pago_total',v_pago,'saldo',v_saldo,'quitado',v_saldo=0);
end;
$$;

grant execute on function public.abrir_caixa(numeric) to authenticated;
grant execute on function public.fechar_caixa(numeric,text) to authenticated;
grant execute on function public.finalizar_venda(uuid,text,uuid,numeric,text,jsonb) to authenticated;
grant execute on function public.ajustar_estoque(uuid,numeric,text) to authenticated;
grant execute on function public.cancelar_venda(bigint,text) to authenticated;
grant execute on function public.receber_fiado(bigint,numeric,text,text) to authenticated;

create or replace view public.vw_vendas_resumo
with (security_invoker = true)
as
select
  v.id,v.created_at,v.status,v.tipo_pagamento,v.subtotal,v.desconto,v.total,v.custo_total,v.lucro,
  v.fiado,v.quitado,ve.nome as vendedor_nome,ve.codigo as vendedor_codigo,c.nome as cliente_nome
from public.vendas v
join public.vendedores ve on ve.id=v.vendedor_id
left join public.clientes c on c.id=v.cliente_id;

grant usage on schema public to authenticated;
grant select on public.profiles,public.vendedores,public.produtos,public.clientes,public.caixas,
  public.vendas,public.venda_itens,public.pagamentos_fiado,public.configuracoes,public.movimentacoes_estoque to authenticated;
grant select on public.vw_vendas_resumo to authenticated;
grant insert,update,delete on public.vendedores,public.produtos,public.clientes,public.configuracoes,public.profiles to authenticated;

-- Restringe execução explícita das operações transacionais ao papel authenticated.
revoke all on function public.abrir_caixa(numeric) from public, anon;
revoke all on function public.fechar_caixa(numeric,text) from public, anon;
revoke all on function public.finalizar_venda(uuid,text,uuid,numeric,text,jsonb) from public, anon;
revoke all on function public.ajustar_estoque(uuid,numeric,text) from public, anon;
revoke all on function public.cancelar_venda(bigint,text) from public, anon;
revoke all on function public.receber_fiado(bigint,numeric,text,text) from public, anon;

grant execute on function public.abrir_caixa(numeric) to authenticated;
grant execute on function public.fechar_caixa(numeric,text) to authenticated;
grant execute on function public.finalizar_venda(uuid,text,uuid,numeric,text,jsonb) to authenticated;
grant execute on function public.ajustar_estoque(uuid,numeric,text) to authenticated;
grant execute on function public.cancelar_venda(bigint,text) to authenticated;
grant execute on function public.receber_fiado(bigint,numeric,text,text) to authenticated;
